/* REGISTER */
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_REGISTER = 'RESET_REGISTER';

/*LOGIN */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

/*PROFILE */
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ADD_SERIES = 'ADD_SERIES';
export const REMOVE_SERIES = 'REMOVE_SERIES';

/*EXPLORE */
export const GET_TODAY = 'GET_TODAY';
export const GET_SEASON = 'GET_SEASON';
export const GET_TOP = 'GET_TOP';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const RESET_MESSAGE = 'RESET_MESSAGE';

/* SELECTED SHOW*/
export const PAGINATE_SUCCESS = 'PAGINATE_SUCCESS';
export const PAGINATE_FAILURE = 'PAGINATE_FAILURE';
export const SET_SELECTED_SHOW = 'SET_SELECTED_SHOW';
